GET http://127.0.0.1:8000/api/authors HTTP/1.1
content-type: application/json

#################################################################

GET http://127.0.0.1:8000/api/authors/2 HTTP/1.1
content-type: application/json

#################################################################

POST http://127.0.0.1:8000/api/authors HTTP/1.1
content-type: application/json

{
  "first_name" : "Juan",
  "last_name" : "Doe",
  "country" : "Argentina",
  "date_of_birth" : "2017-05-14"
}

#################################################################

PUT http://127.0.0.1:8000/api/authors/6 HTTP/1.1
content-type: application/json

{
  "first_name": "Jhon",
  "last_name": "Doe",
  "country": "US",
  "date_of_birth": "2017-05-14"
}

#################################################################

DELETE http://127.0.0.1:8000/api/authors/3 HTTP/1.1
content-type: application/json
